name: Super Linter

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

jobs:
    lint:
        name: Run GitHub Super-Linter
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2
              with:
                  fetch-depth: 0

            - name: Run Super-Linter
              uses: super-linter/super-linter@v7.3.0
              env:
                  VALIDATE_ALL_CODEBASE: false
                  DEFAULT_BRANCH: master, main
                  VALIDATE_CSHARP: true
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
