name: Unity Tests

on: [push, pull_request, workflow_dispatch]

jobs:
    testAllModes:
        name: Test in ${{ matrix.testMode }}
        runs-on: ubuntu-latest
        permissions:
            contents: read
            checks: write
            id-token: write
            pull-requests: write
        strategy:
            fail-fast: false
            matrix:
                projectPath:
                    - .
                testMode:
                    - playmode
                    - editmode
                    - standalone
        steps:
            - uses: actions/checkout@v4
              with:
                  lfs: true
            - uses: actions/cache@v3
              with:
                  path: ${{ matrix.projectPath }}/Library
                  key: Library-${{ matrix.projectPath }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
                  restore-keys: |
                      Library-${{ matrix.projectPath }}-
                      Library-
            - uses: game-ci/unity-test-runner@v4
              id: tests
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                  projectPath: ${{ matrix.projectPath }}
                  testMode: ${{ matrix.testMode }}
                  githubToken: ${{ secrets.GITHUB_TOKEN }}
                  checkName: ${{ matrix.testMode }} Test Results
                  # No coverage options to avoid generating artifacts
                  # No artifactsPath specified to avoid collecting artifacts
            # Removed the artifact upload steps
